language: cpp
sudo: false
git:
    submodules: false

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
            - kubuntu-backports
        packages: &default_packages
            - libedit-dev
            - g++-4.9
            - gcc-4.9

matrix:
    include:
        env: CAIDE_LLVM_VER=3.6
        packages:
            - *default_packages
            - libclang-3.6-dev
            - llvm-3.6-dev
    include:
        env: CAIDE_LLVM_VER=3.7
        packages:
            - *default_packages
            - libclang-3.7-dev
            - llvm-3.7-dev
    include:
        env: CAIDE_LLVM_VER=GIT
        packages:
            - *default_packages
            - cmake


script:  travis/build-and-test.sh

notifications:
    on_failure: always
    email:
        on_success: always

