language: cpp
sudo: false
git:
    submodules: false

apt:
    sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
    packages:
        - libclang-3.7-dev
        - llvm-3.7-dev
        - g++-4.8
        - gcc-4.8

install: travis/install-prerequisites.sh
script:  travis/build-and-test.sh

notifications:
    on_failure: always
    email:
        on_success: always

