language: cpp
sudo: false
git:
    submodules: false

addons:
    apt:
        sources: &default_sources
            - ubuntu-toolchain-r-test
        packages: &default_packages
            - g++-4.9
            - gcc-4.9
            - binutils

matrix:
    include:
        - env: CAIDE_USE_SYSTEM_CLANG=OFF
          addons:
              apt:
                  sources:
                      - *default_sources
                      - kubuntu-backports
                  packages:
                      - *default_packages
                      - cmake

        - env: CAIDE_USE_SYSTEM_CLANG=ON CAIDE_CLANG_VERSION=3.6
          addons:
              apt:
                  sources:
                      - *default_sources
                      - llvm-toolchain-precise-3.6
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-3.6-dev
                      - llvm-3.6-dev

        - env: CAIDE_USE_SYSTEM_CLANG=ON CAIDE_CLANG_VERSION=3.7
          addons:
              apt:
                  sources:
                      - *default_sources
                      - llvm-toolchain-precise-3.7
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-3.7-dev
                      - llvm-3.7-dev


script:  travis/build-and-test.sh

notifications:
    on_failure: always
    email:
        on_success: always

