language: cpp
dist: trusty
sudo: required
git:
    submodules: false

addons:
    apt:
        sources: &default_sources
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:george-edison55/cmake-3.x'
        packages: &default_packages
            - g++-4.9
            - gcc-4.9
            - binutils
            - cmake

matrix:
    include:
        - env: CAIDE_USE_SYSTEM_CLANG=OFF
        - env: CAIDE_CLANG_VERSION=3.6 CAIDE_USE_SYSTEM_CLANG=ON
          addons:
              apt:
                  sources:
                      - *default_sources
                      - llvm-toolchain-precise-3.6
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-3.6-dev
                      - llvm-3.6-dev

        - env: CAIDE_CLANG_VERSION=3.7 CAIDE_USE_SYSTEM_CLANG=ON
          addons:
              apt:
                  sources:
                      - *default_sources
                      - llvm-toolchain-precise-3.7
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-3.7-dev
                      - llvm-3.7-dev

        - env: CAIDE_CLANG_VERSION=3.8 CAIDE_USE_SYSTEM_CLANG=ON
          addons:
              apt:
                  sources:
                      - *default_sources
                      - llvm-toolchain-precise-3.8
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-3.8-dev
                      - llvm-3.8-dev

        - env: CAIDE_CLANG_VERSION=3.9 CAIDE_USE_SYSTEM_CLANG=ON
          addons:
              apt:
                  sources:
                      - *default_sources
                      - llvm-toolchain-precise-3.9
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-3.9-dev
                      - llvm-3.9-dev

        - env: CAIDE_CLANG_VERSION=4.0 CAIDE_USE_SYSTEM_CLANG=ON
          addons:
              apt:
                  sources:
                      - *default_sources
                      - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
                        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
                  packages:
                      - *default_packages
                      - libedit-dev
                      - libclang-4.0-dev
                      - llvm-4.0-dev
    allow_failures:
        - env: CAIDE_CLANG_VERSION=3.8 CAIDE_USE_SYSTEM_CLANG=ON
        - env: CAIDE_CLANG_VERSION=3.9 CAIDE_USE_SYSTEM_CLANG=ON
        - env: CAIDE_CLANG_VERSION=4.0 CAIDE_USE_SYSTEM_CLANG=ON
    fast_finish: true


script:  travis/build-and-test.sh

notifications:
    email:
        on_failure: always

